# Generated by Django 4.2.7 on 2023-11-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
